### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Creepinevil** [twisterghost/patchwire-gm#1]
Greetings, 
I'm relatively new to networking and just trying to get a grasp on things.
I noticed you are storing each command event in a separate script file.
[net_handle_command.gml#L12](https://github.com/twisterghost/patchwire-gm/blob/ac355418f7fb8323f997099d06fb9a54035d9381/src/net_handle_command.gml#L12)
Aside from creating many files, does this increase network performance?
I was thinking about passing `(handler, argument1)` to a single script with a switch.
This way there would be less files to manage. Then I got to thinking that every time a command is called it would have to load a large script.

**Comment by twisterghost** [comment]
It's up to you how you want to structure your network handlers, but generally it won't be an issue to pass the command handlers to individual scripts. The bigger impact would be startup time, but its mostly negligible unless you have thousands of handler scripts.

A big switch statement would just become unwieldy after a while, so leaning towards individual handler scripts seems like a good way to structure the logic of the game.

Sorry for the terribly late response.
