### ISSUE TITLE
HTML5 module support

### ISSUE THREAD

**Issue by Josh1billion** [twisterghost/patchwire-gm#2]
It looks like the game can't connect when exporting as an HTML5 game.  Is there a plan to add support?  I understand if it's virtually impossible with how GM does its networking.

**Comment by twisterghost** [comment]
I haven't played much with the HTML5 module, but I've just begin re-investing some time into Patchwire-GM. I'll look into this a bit and get back to you with what I find. Sorry for the horrifically late response.

**Comment by twisterghost** [comment]
As of now, GM:S still does not support networking natively in the HTML5 module. However, you may be able to get some use out of this: https://marketplace.yoyogames.com/assets/4569/socket-io-client-for-html5

Closing this, but will keep an eye on the networking stack for the HTML5 module.
