### ISSUE TITLE
Error - Data Structure with Index does not exist

### ISSUE THREAD

**Issue by tutchmedia** [twisterghost/patchwire-gm#4]
Hi, i have the server running and have launched the GM client locally and added the create scripts but when i run, i get the following message:

```
############################################################################################
ERROR in
action number 1
of Create Event
for object obj_network_manager:

Data structure with index does not exist.
 at gml_Script_net_cmd_parse (line 4) - var netResponseType = ds_map_find_value(async_load, "type");
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_net_cmd_parse (line 4)
called from - gml_Script_net_cmd_resolve (line 4) - var netResponse = net_cmd_parse();
called from - gml_Object_obj_network_manager_Create_0 (line 8) - net_cmd_resolve();
```

What am i doing wrong please? 💃

**Comment by tutchmedia** [comment]
Actually, nevermind - it was me being silly and not having the net_cmd_resolve() code in the networking script :) Thanks

**Comment by twisterghost** [comment]
Glad I could help!

**Comment by tutchmedia** [comment]
@twisterghost - I'm sure i'll be having more problems and reaching out. Excited about using it.

Quick question - what happened to patchwire.io ?

**Comment by twisterghost** [comment]
I let the domain run out for now, as I'm re-aligning these packages under the gm-core name. All it did was redirect to the github repo, anyway. I'd like to get a real docs website up in the forseable future.

**Comment by tutchmedia** [comment]
Sounds awesome! Appreciate all the support - i was however, wondering if you had any further docs related to getting 2 player objects moving around over the network? I've just been playing with the GM-Demo you made with the chat and it's pretty amazing but was wondering how to adapt it to get x and y positions shared?

**Comment by twisterghost** [comment]
At the most basic, its just a matter of sending x and y positions when they change instead of sending chat messages, then on the receiving end, updating the object's position to those x and y positions, by having the server send back out the updated x and y positions as sent from the client.
