### ISSUE TITLE
Do this extension use IPv6? So it can be used in ios?

### ISSUE THREAD

**Issue by The-any-Key** [twisterghost/patchwire-gm#5]
Short question. Can this module use IPv6? As ios app store demand that you use IPv6?

**Comment by twisterghost** [comment]
To my knowledge, GameMaker does not yet support ipv6 on TCP/UDP functions which patchwire relies on. I would encourage you to try it or log an issue with YoYoGames, but from what I have found, ipv6 support is only available for http commands.

**Comment by twisterghost** [comment]
Going to close this issue. If you find out more info, let me know and if I there are changes that can be done to support IPv6, I can look into it.
