### ISSUE TITLE
I have trouble using it with Game Maker Studio 2

### ISSUE THREAD

**Issue by yokun51** [twisterghost/patchwire-gm#6]
Hello, I know your wiki is greatly explaining all, but I really don't understand how to use it with GMS.Do I have to make a command handler in the game maker object and the node.js server to make it work? Or can I automatically broadcast all received commands? 

How can I know wich client is sending something to move player with their x ans y value?

Do yoy have a demo that show how to do it basically?

That's the part I'm confused about.Thank you for your time and your good work.

Sorry if my english isn't perfect.

**Comment by twisterghost** [comment]
Hey @yokun51! Have you given a read through the [gmcore.io](https://gmcore.io/patchwire/) docs? They should walk through how to set things up. 

From there, the [Patchwire Server Wiki](https://github.com/twisterghost/patchwire/wiki) goes over the API details for the Node.js side.

I would be happy to put together a simple working example project when I get some time to do so. But until then, in short, when a `Client` joins on the server side, you will want to add it to a `ClientManager`, and you can use `.set(key, value)` on the client object to set any data you would like, such as a User ID. Then, your server code can use `.get(key)` on the client object to read data back, like the User ID, and use that to know which client is sending what command.

The `ClientManager` has a function called `addCommandListener` which registers a callback for a given command type. The callback function will be given the `Client` instance that send the command, so you can read the client ID off of that:

https://github.com/twisterghost/patchwire/wiki/ClientManager#addcommandlistenerstring-command-functionclient-client-object-data-handler

I'll try to find some time this weekend to make a simple GMS2 + Node.js project and push it up to Github to share.

**Comment by yokun51** [comment]
Thank you very much for your advice, I understand better how it works now.

Sorry to ask so many questions, but how do you send data to a specific client?

Let's imagine I have two players connected to my server and I want to send their position (x, y) from one to the other so they can see each other in the games.

First, should I use Tick Mode?

Second, how do I make sure that the client sending the command doesn't receive it back?
Or
How to make sure that when connecting to the server, the player receives his clientID.

How should I set take?

Thanks you for your help and a demo would be great.

**Comment by yokun51** [comment]
Yes, I have read the gmcore.io documentation and thank you, I understand better how it works now.

I have another question:
How do I get 2 or more players to be on the same map and send their coordinates (x,y) using this?

Do I have to make a client be the server that handles all the logic?

Do I need to worry about the number of packets (commands) I send or receive if I use one client to control everything?

Thank you for your help.
